module.exports = {
  breaches: [
    {
      Name: 'Adobe',
      Title: 'Adobe',
      Domain: 'adobe.com',
      BreachDate: '2013-10-04',
      AddedDate: '2013-12-04T00:00:00Z',
      ModifiedDate: '2022-05-15T23:52:49Z',
      PwnCount: 152445165,
      Description: 'In October 2013, 153 million Adobe accounts were breached with each containing an internal ID, username, email, <em>encrypted</em> password and a password hint in plain text. The password cryptography was poorly done and many were quickly resolved back to plain text. The unencrypted hints also <a href="http://www.troyhunt.com/2013/11/adobe-credentials-and-serious.html" target="_blank" rel="noopener">disclosed much about the passwords</a> adding further to the risk that hundreds of millions of Adobe customers already faced.',
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/Adobe.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'Canva',
      Title: 'Canva',
      Domain: 'canva.com',
      BreachDate: '2019-05-24',
      AddedDate: '2019-08-09T14:24:01Z',
      ModifiedDate: '2019-08-09T14:24:01Z',
      PwnCount: 137272116,
      Description: 'In May 2019, the graphic design tool website <a href="https://support.canva.com/contact/customer-support/may-24-security-incident-faqs/" target="_blank" rel="noopener">Canva suffered a data breach</a> that impacted 137 million subscribers. The exposed data included email addresses, usernames, names, cities of residence and passwords stored as bcrypt hashes for users not using social logins. The data was provided to HIBP by a source who requested it be attributed to "JimScott.Sec@protonmail.com".',
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/Canva.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'PDL',
      Title: 'Data Enrichment Exposure From PDL Customer',
      Domain: '',
      BreachDate: '2019-10-16',
      AddedDate: '2019-11-22T20:13:04Z',
      ModifiedDate: '2019-11-22T20:13:04Z',
      PwnCount: 622161052,
      Description: `In October 2019, <a href="https://www.troyhunt.com/data-enrichment-people-data-labs-and-another-622m-email-addresses" target="_blank" rel="noopener">security researchers Vinny Troia and Bob Diachenko identified an unprotected Elasticsearch server holding 1.2 billion records of personal data</a>. The exposed data included an index indicating it was sourced from data enrichment company People Data Labs (PDL) and contained 622 million unique email addresses. The server was not owned by PDL and it's believed a customer failed to properly secure the database. Exposed information included email addresses, phone numbers, social media profiles and job history data.`,
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'Dropbox',
      Title: 'Dropbox',
      Domain: 'dropbox.com',
      BreachDate: '2012-07-01',
      AddedDate: '2016-08-31T00:19:19Z',
      ModifiedDate: '2016-08-31T00:19:19Z',
      PwnCount: 68648009,
      Description: 'In mid-2012, Dropbox suffered a data breach which exposed the stored credentials of tens of millions of their customers. In August 2016, <a href="https://motherboard.vice.com/read/dropbox-forces-password-resets-after-user-credentials-exposed" target="_blank" rel="noopener">they forced password resets for customers they believed may be at risk</a>. A large volume of data totalling over 68 million records <a href="https://motherboard.vice.com/read/hackers-stole-over-60-million-dropbox-accounts" target="_blank" rel="noopener">was subsequently traded online</a> and included email addresses and salted hashes of passwords (half of them SHA1, half of them bcrypt).',
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/Dropbox.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'Dubsmash',
      Title: 'Dubsmash',
      Domain: 'dubsmash.com',
      BreachDate: '2018-12-01',
      AddedDate: '2019-02-25T08:35:58Z',
      ModifiedDate: '2019-02-25T08:35:58Z',
      PwnCount: 161749950,
      Description: 'In December 2018, the video messaging service <a href="https://www.theregister.co.uk/2019/02/11/620_million_hacked_accounts_dark_web/" target="_blank" rel="noopener">Dubsmash suffered a data breach</a>. The incident exposed 162 million unique email addresses alongside usernames and PBKDF2 password hashes. In 2019, the data appeared listed for sale on a dark web marketplace (along with several other large breaches) and subsequently began circulating more broadly. The data was provided to HIBP by a source who requested it to be attributed to &quot;BenjaminBlue@exploit.im&quot;.',
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/Dubsmash.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'GeekedIn',
      Title: 'GeekedIn',
      Domain: 'geekedin.net',
      BreachDate: '2016-08-15',
      AddedDate: '2016-11-17T19:44:24Z',
      ModifiedDate: '2022-03-06T05:21:27Z',
      PwnCount: 1073164,
      Description: `In August 2016, the technology recruitment site GeekedIn left a MongoDB database exposed and over 8M records were extracted by an unknown third party. The breached data was originally scraped from GitHub in violation of their terms of use and contained information exposed in public profiles, including over 1 million members' email addresses. Full details on the incident (including how impacted members can see their leaked data) are covered in the blog post on <a href="https://www.troyhunt.com/8-million-github-profiles-were-leaked-from-geekedins-mongodb-heres-how-to-see-yours" target="_blank" rel="noopener">8 million GitHub profiles were leaked from GeekedIn's MongoDB - here's how to see yours</a>.`,
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/GeekedIn.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'Gravatar',
      Title: 'Gravatar',
      Domain: 'gravatar.com',
      BreachDate: '2020-10-03',
      AddedDate: '2021-12-05T22:45:58Z',
      ModifiedDate: '2021-12-08T01:47:02Z',
      PwnCount: 113990759,
      Description: `In October 2020, <a href="https://www.bleepingcomputer.com/news/security/online-avatar-service-gravatar-allows-mass-collection-of-user-info/" target="_blank" rel="noopener">a security researcher published a technique for scraping large volumes of data from Gravatar, the service for providing globally unique avatars </a>. 167 million names, usernames and MD5 hashes of email addresses used to reference users' avatars were subsequently scraped and distributed within the hacking community. 114 million of the MD5 hashes were cracked and distributed alongside the source hash, thus disclosing the original email address and accompanying data. Following the impacted email addresses being searchable in HIBP, <a href="https://en.gravatar.com/support/data-privacy" target="_blank" rel="noopener">Gravatar release an FAQ detailing the incident</a>.`,
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/Gravatar.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'LinkedInScrape',
      Title: 'LinkedIn Scraped Data',
      Domain: 'linkedin.com',
      BreachDate: '2021-04-08',
      AddedDate: '2021-10-02T21:39:21Z',
      ModifiedDate: '2021-10-02T21:48:03Z',
      PwnCount: 125698496,
      Description: 'During the first half of 2021, <a href="https://www.businessinsider.com.au/linkedin-data-scraped-500-million-users-for-sale-online-2021-4" target="_blank" rel="noopener">LinkedIn was targeted by attackers who scraped data from hundreds of millions of public profiles and later sold them online</a>. Whilst the scraping did not constitute a data breach nor did it access any personal data not intended to be publicly accessible, the data was still monetised and later broadly circulated in hacking circles. The scraped data contains approximately 400M records with 125M unique email addresses, as well as names, geographic locations, genders and job titles. LinkedIn specifically addresses the incident in their post on <a href="https://news.linkedin.com/2021/june/an-update-from-linkedin" target="_blank" rel="noopener">An update on report of scraped data</a>.',
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/LinkedIn.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'PhoneHouse',
      Title: 'Phone House España',
      Domain: 'phonehouse.es',
      BreachDate: '2021-04-08',
      AddedDate: '2021-04-22T05:59:07Z',
      ModifiedDate: '2021-04-22T05:59:07Z',
      PwnCount: 5223350,
      Description: 'In April 2021, the Spanish retailer <a href="https://thetechzone.online/cyberattack-on-phone-house-with-ransomware-and-possible-data-breach/" target="_blank" rel="noopener">Phone House allegedly suffered a ransomware attack that also exposed significant volumes of customer data</a>. Attributed to the Babuk ransomware, a collection of data alleged to be a subset of a larger corpus was posted to a dark web site and contained 5.2M email addresses along with names, nationalities, genders, dates of birth, phone numbers and physical addresses. Phone House has been threatened with further releases if a ransom is not paid.',
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/PhoneHouse.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    },
    {
      Name: 'Taringa',
      Title: 'Taringa',
      Domain: 'taringa.net',
      BreachDate: '2017-08-01',
      AddedDate: '2018-04-19T10:11:37Z',
      ModifiedDate: '2018-04-19T10:11:37Z',
      PwnCount: 27971100,
      Description: `In September 2017, news broke that <a href="https://thehackernews.com/2017/09/taringa-data-breach-hacking.html" target="_blank" rel="noopener">Taringa had suffered a data breach exposing 28 million records</a>. Known as &quot;The Latin American Reddit&quot;, <a href="https://www.taringa.net/posts/taringa/19972402/Un-mensaje-importante-sobre-la-seguridad-de-tu-cuenta.html" target="_blank" rel="noopener">Taringa's breach disclosure notice</a> indicated the incident dated back to August that year. The exposed data included usernames, email addresses and weak MD5 hashes of passwords.`,
      LogoPath: 'https://haveibeenpwned.com/Content/Images/PwnedLogos/Taringa.png',
      DataClasses: [Array],
      IsVerified: true,
      IsFabricated: false,
      IsSensitive: false,
      IsRetired: false,
      IsSpamList: false,
      IsMalware: false
    }
  ],
  pastes: null
}